services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./conf/nginx.conf.template:/etc/nginx/templates/default.conf.template
      - ./phishing_emails.pdf:/usr/share/nginx/html/phishing_emails.pdf
    restart: unless-stopped
